apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: educonnect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nasirbloch323/educonnect:v1
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt-secret
