/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/EnMBluQXt2B
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"

export function Component() {
  return (
    (<div className="space-y-8">
      <div className="space-y-4">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold">Admission Form</h1>
          <p className="text-gray-500 dark:text-gray-400">Enter your information to apply</p>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="first-name">First name</Label>
            <Input id="first-name" placeholder="Enter your first name" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="last-name">Last name</Label>
            <Input id="last-name" placeholder="Enter your last name" required />
          </div>
        </div>
        <div className="grid grid-cols-3 gap-4">
          <div className="space-y-2">
            <Label htmlFor="dob">Date of birth</Label>
            <Input id="dob" type="date" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="nationality">Nationality</Label>
            <Input id="nationality" placeholder="Enter your nationality" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="gender">Gender</Label>
            <Select>
              <SelectTrigger id="gender">
                <SelectValue placeholder="Select" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="male">Male</SelectItem>
                <SelectItem value="female">Female</SelectItem>
                <SelectItem value="other">Other</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="address">Address</Label>
          <Textarea id="address" placeholder="Enter your address" required />
        </div>
      </div>
      <div className="space-y-4">
        <div className="space-y-2">
          <h2 className="text-2xl font-bold">Educational Background</h2>
          <p className="text-gray-500 dark:text-gray-400">Enter your educational information</p>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="institution">Institution</Label>
            <Input id="institution" placeholder="Enter your institution" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="course">Course</Label>
            <Input id="course" placeholder="Enter your course" required />
          </div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="start-year">Start year</Label>
            <Input
              id="start-year"
              placeholder="Enter your start year"
              required
              type="number" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="end-year">End year</Label>
            <Input id="end-year" placeholder="Enter your end year" required type="number" />
          </div>
        </div>
      </div>
      <div className="space-y-4">
        <div className="space-y-2">
          <h2 className="text-2xl font-bold">Contact Details</h2>
          <p className="text-gray-500 dark:text-gray-400">Enter your contact information</p>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="phone">Phone</Label>
            <Input id="phone" placeholder="Enter your phone number" required type="tel" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="Enter your email" required type="email" />
          </div>
        </div>
      </div>
      <div className="space-y-4">
        <div className="space-y-2">
          <h2 className="text-2xl font-bold">Upload Documents</h2>
          <p className="text-gray-500 dark:text-gray-400">Please upload the following documents</p>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="transcript">Transcript</Label>
            <Input accept=".pdf" id="transcript" type="file" />
            <p className="text-sm text-gray-500 dark:text-gray-400">Please upload your transcript in PDF format</p>
          </div>
          <div className="space-y-2">
            <Label htmlFor="certificate">Certificate</Label>
            <Input accept=".pdf" id="certificate" type="file" />
            <p className="text-sm text-gray-500 dark:text-gray-400">Please upload your certificate in PDF format</p>
          </div>
          <div className="space-y-2">
            <Label htmlFor="id">Identification</Label>
            <Input accept=".pdf" id="id" type="file" />
            <p className="text-sm text-gray-500 dark:text-gray-400">Please upload your identification in PDF format</p>
          </div>
        </div>
      </div>
    </div>)
  );
}
